# Generated by Django 3.1 on 2020-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='link',
        ),
        migrations.AddField(
            model_name='section',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
