# Generated by Django 3.1 on 2020-08-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sub_title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
