# Generated by Django 3.1 on 2020-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_section_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='Joseph T Mohan BS.c', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default='WEB DEVELPER', max_length=256),
            preserve_default=False,
        ),
    ]
