# Generated by Django 3.1 on 2020-08-19 17:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200819_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
