# Generated by Django 3.1 on 2020-08-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200819_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_image', to='main.section')),
            ],
        ),
    ]
