# Generated by Django 3.1 on 2020-08-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sectionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlink',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='section_link', to='main.section'),
            preserve_default=False,
        ),
    ]
