# Generated by Django 3.1 on 2020-08-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sectionlink_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
    ]
