# Generated by Django 3.1 on 2020-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200827_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
