# Generated by Django 3.1 on 2020-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200828_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
