# Generated by Django 3.1 on 2020-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200828_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
